battlecruisers/yanullja

README.md

docs(readme): 팀 프로필 템플릿 추가

---

README.md

docs(readme.md): add self-introduce

---

README.md

docs(readme.md): 김민우 자기소개 하기

---

README.md

docs(readme): venus 자기소개

---

src/main/java/com/battlecruisers/yanullja/place/Place.java
src/main/java/com/battlecruisers/yanullja/room/Room.java

객실(Room), 장소(Place) 엔티티 추가했습니다!

feat(Place, Room): Create Entity

---

src/main/java/com/battlecruisers/yanullja/coupon/Coupon.java

feat(Coupon) : Create Entity

---

src/main/java/com/battlecruisers/yanullja/mainregion/domain/MainRegion.java
src/main/java/com/battlecruisers/yanullja/place/domain/Place.java
src/main/java/com/battlecruisers/yanullja/room/domain/Room.java
src/main/java/com/battlecruisers/yanullja/roominfo/domain/RoomInfo.java
src/main/java/com/battlecruisers/yanullja/roominfo/domain/UsageDayType.java
src/main/java/com/battlecruisers/yanullja/subregion/domain/SubRegion.java

- 객실 정보 엔티티 생성
- 객실과 객실 정보 엔티티 연관관계 설정
- 기존의 객실, 숙소, 메인 지역, 서브 지역 엔티티 BaseDate 상속

feat(RoomInfo) / create room info Entity

---

.github/workflows/cicd.yml

main 으로 머지 시 서버에 자동으로 배포되도록 설정했습니다.
closes #41

build(cicd): add automatic deployment

---

build.gradle
src/main/java/com/battlecruisers/yanullja/config/QueryDslConfig.java

QueryDsl 초기 세팅 진행했습니다.
코드 pull하시고
1. build.gradle에서 코끼리 누르시고 업데이트 진행
2. 인텔리제이 우측에 있는 코끼리 버튼(Gradle) 누르시고 -> Tasks -> build -> clean 으로 기존 빌드파일 삭제
3. Tasks -> build -> build으로 새로 빌드
4. /build/classes/java/main/com/battlecruisers/yanullja/각자 도메인 파일에서 도메인이름에 Q가 붙은도메인이 생기면 성공!

feat(QueryDsl): initial QueryDsl setup

---

server/src/main/java/com/battlecruisers/yanullja/review/ReviewService.java
server/src/main/java/com/battlecruisers/yanullja/room/RoomService.java
server/src/main/java/com/battlecruisers/yanullja/room/domain/RoomController.java
server/src/main/java/com/battlecruisers/yanullja/roominfo/domain/RentalType.java
server/src/main/java/com/battlecruisers/yanullja/roominfo/domain/RoomInfo.java

Room, Review Controller 및 Service 생성
RentalType Enum 클래스 생성 및 RoomInfo에 rentalType 프로퍼티 추가.

feat(room, review, roominfo): Add controller and service, create rentalType

---

server/build.gradle
server/src/main/java/com/battlecruisers/yanullja/place/domain/Place.java
server/src/main/java/com/battlecruisers/yanullja/region/MainRegionRepository.java
server/src/main/java/com/battlecruisers/yanullja/region/RegionService.java
server/src/main/java/com/battlecruisers/yanullja/region/SubRegionRepository.java
server/src/main/java/com/battlecruisers/yanullja/region/domain/MainRegion.java
server/src/main/java/com/battlecruisers/yanullja/region/domain/SubRegion.java
server/src/main/java/com/battlecruisers/yanullja/region/dto/RegionQueryDto.java

https://github.com/battlecruisers/yanullja/issues/60
지역 관련 이슈 구현 완료했습니다.

feat(add-query-region): Add Region Query

---

server/src/main/java/com/battlecruisers/yanullja/home/HomeController.java
server/src/main/java/com/battlecruisers/yanullja/member/MemberController.java
server/src/main/java/com/battlecruisers/yanullja/member/MemberNotFoundException.java
server/src/main/java/com/battlecruisers/yanullja/member/MemberRepository.java
server/src/main/java/com/battlecruisers/yanullja/member/MemberService.java

멤버 도메인 만들었습니다!
우선은 시큐리티를 붙이기 전에 mock으로 /members/me를 호출할 수 있도록 Long id = 1L로 고정해뒀습니다.
각자 개발환경 디비에서 아이디가 1인 멤버를 추가하시면 됩니다!

feat(member/*): Create member service & controller

---

.github/workflows/cicd.yml

build(cicd): auto deploy both client and server

---

server/src/main/java/com/battlecruisers/yanullja/home/HomeController.java

이제 서버에 접속하기만 하면 
(https://api.yanullja.com/) 
스웨거로 바로 리다이렉트 됩니다.
closes  #81

feat(HomeController): / redirect to swagger

---

server/src/main/java/com/battlecruisers/yanullja/member/domain/Member.java
server/src/main/java/com/battlecruisers/yanullja/purchase/domain/PayType.java
server/src/main/java/com/battlecruisers/yanullja/purchase/domain/Purchase.java
server/src/main/java/com/battlecruisers/yanullja/purchase/dto/PurchaseDto.java
server/src/main/java/com/battlecruisers/yanullja/reservation/domain/Reservation.java
server/src/main/java/com/battlecruisers/yanullja/reservation/dto/ReservationDto.java
server/src/main/java/com/battlecruisers/yanullja/room/domain/Room.java

Feat(purchase, reservation) create entity

---

server/src/main/java/com/battlecruisers/yanullja/coupon/CouponController.java
server/src/main/java/com/battlecruisers/yanullja/coupon/CouponService.java
server/src/main/java/com/battlecruisers/yanullja/coupon/MemberCouponController.java
server/src/main/java/com/battlecruisers/yanullja/coupon/MemberCouponRepository.java
server/src/main/java/com/battlecruisers/yanullja/coupon/MemberCouponService.java
server/src/main/java/com/battlecruisers/yanullja/coupon/domain/Coupon.java
server/src/main/java/com/battlecruisers/yanullja/coupon/domain/MemberCoupon.java
server/src/main/java/com/battlecruisers/yanullja/coupon/domain/RoomType.java
server/src/main/java/com/battlecruisers/yanullja/coupon/dto/CouponRequestDto.java
server/src/main/java/com/battlecruisers/yanullja/coupon/dto/CouponResponseDto.java
server/src/main/java/com/battlecruisers/yanullja/coupon/exception/AlreadyUsedException.java
server/src/main/java/com/battlecruisers/yanullja/coupon/exception/CouponUsageHistoryNotFoundException.java
server/src/main/java/com/battlecruisers/yanullja/coupon/exception/InvalidCouponException.java
server/src/main/java/com/battlecruisers/yanullja/coupon/exception/MemberCouponNotFoundException.java
server/src/main/java/com/battlecruisers/yanullja/coupon/exception/NoAvailableCouponsException.java
server/src/main/java/com/battlecruisers/yanullja/member/MemberController.java
server/src/main/java/com/battlecruisers/yanullja/member/MemberService.java
server/src/main/java/com/battlecruisers/yanullja/member/domain/Member.java
server/src/main/java/com/battlecruisers/yanullja/member/dto/MemberUpdateDto.java

feat(Coupon, MemberCoupon) : Coupon, MemberCoupon Rest Api 개발

---

server/build.gradle
server/src/main/java/com/battlecruisers/yanullja/coupon/CouponService.java
server/src/main/java/com/battlecruisers/yanullja/coupon/dto/CouponMapper.java
server/src/main/java/com/battlecruisers/yanullja/coupon/dto/CouponResponseDto.java

feat(mapstruct): install mapstruct dependency

---

server/src/main/java/com/battlecruisers/yanullja/reservation/ReservationController.java
server/src/main/java/com/battlecruisers/yanullja/reservation/ReservationRepository.java
server/src/main/java/com/battlecruisers/yanullja/reservation/ReservationService.java
server/src/main/java/com/battlecruisers/yanullja/reservation/domain/Reservation.java
server/src/main/java/com/battlecruisers/yanullja/reservation/domain/ReservationStatus.java
server/src/main/java/com/battlecruisers/yanullja/reservation/dto/ReservationRequestDto.java
server/src/main/java/com/battlecruisers/yanullja/reservation/exception/ErrorCode.java
server/src/main/java/com/battlecruisers/yanullja/reservation/exception/NotEnoughRoomCapacityException.java
server/src/main/java/com/battlecruisers/yanullja/reservation/exception/StartDateNotAfterTodayException.java
server/src/main/java/com/battlecruisers/yanullja/reservation/exception/StartDateNotBeforeEndDateException.java
server/src/main/java/com/battlecruisers/yanullja/room/domain/Room.java

feat(reservation): Reservation 예약 기능 구현

---

server/src/main/java/com/battlecruisers/yanullja/place/domain/Place.java
server/src/main/java/com/battlecruisers/yanullja/review/CustomReviewRepository.java
server/src/main/java/com/battlecruisers/yanullja/review/CustomReviewRepositoryImpl.java
server/src/main/java/com/battlecruisers/yanullja/review/ReviewController.java
server/src/main/java/com/battlecruisers/yanullja/review/ReviewService.java
server/src/main/java/com/battlecruisers/yanullja/review/domain/Review.java
server/src/main/java/com/battlecruisers/yanullja/review/dto/ReviewDetailDto.java
server/src/main/java/com/battlecruisers/yanullja/review/dto/ReviewSaveDto.java
server/src/main/java/com/battlecruisers/yanullja/review/dto/ReviewStatisticsDto.java
server/src/main/java/com/battlecruisers/yanullja/review/exception/NoReviewsException.java
server/src/main/java/com/battlecruisers/yanullja/room/domain/Room.java
server/src/test/java/com/battlecruisers/yanullja/YanulljaApplicationTests.java

1. 리뷰 등록 기능 추가
2. Dto-Entity 변환 메소드 이름 변경
3. ReviewInfo클래스 -> ReivewStatisticsDto로 변경

feat(Review): 리뷰 등록 기능 추가 및 Dto <-> Entity 변환 메소드명 변경

---

server/src/main/java/com/battlecruisers/yanullja/coupon/CouponController.java
server/src/main/java/com/battlecruisers/yanullja/coupon/CouponService.java
server/src/main/java/com/battlecruisers/yanullja/coupon/MemberCouponController.java
server/src/main/java/com/battlecruisers/yanullja/coupon/MemberCouponRepository.java
server/src/main/java/com/battlecruisers/yanullja/coupon/MemberCouponService.java
server/src/main/java/com/battlecruisers/yanullja/coupon/domain/MemberCoupon.java
server/src/main/java/com/battlecruisers/yanullja/coupon/domain/RoomType.java
server/src/main/java/com/battlecruisers/yanullja/coupon/dto/MemberCouponResponseDto.java
server/src/main/java/com/battlecruisers/yanullja/coupon/exception/InvalidAccessException.java
server/src/main/java/com/battlecruisers/yanullja/place/PlaceService.java
server/src/main/java/com/battlecruisers/yanullja/room/dto/RoomQueryDto.java

feat(MemberCoupon) : 회원이 사용 가능한 쿠폰목록 조회

---

server/.gitignore
server/build.gradle
server/src/main/java/com/battlecruisers/yanullja/auth/CustomAuthenticationFilter.java
server/src/main/java/com/battlecruisers/yanullja/auth/controller/AuthController.java
server/src/main/java/com/battlecruisers/yanullja/auth/dto/LoginDto.java
server/src/main/java/com/battlecruisers/yanullja/common/logging/HttpLoggingFilter.java
server/src/main/java/com/battlecruisers/yanullja/common/security/MockUserDetailsService.java
server/src/main/java/com/battlecruisers/yanullja/common/security/SpringSecurityConfig.java
server/src/main/java/com/battlecruisers/yanullja/member/MemberRepository.java
server/src/main/resources/application.yml

UsernamePasswordAuthenticationFilter를 이용해 Mock login을 구현했습니다.
- POST /auth/login: 로그인
- POST /auth/logout: 로그아웃
- GET /auth: 현재 로그인된 유저 정보

feat(auth/*): support mock login

---

server/src/main/java/com/battlecruisers/yanullja/coupon/CouponController.java
server/src/main/java/com/battlecruisers/yanullja/coupon/CouponService.java
server/src/main/java/com/battlecruisers/yanullja/coupon/MemberCouponController.java
server/src/main/java/com/battlecruisers/yanullja/coupon/MemberCouponService.java
server/src/main/java/com/battlecruisers/yanullja/coupon/domain/Coupon.java
server/src/main/java/com/battlecruisers/yanullja/coupon/dto/CouponDto.java
server/src/main/java/com/battlecruisers/yanullja/coupon/dto/MemberCouponDto.java

refactor(CouponService, MemberCouponService) : 서비스단에 위치한 불필요한 코드 삭제 및 수정

refactor(CouponService, MemberCouponService) : 서비스단에 위치한 불필요한 코드 삭제 및 수정

---

server/build.gradle
server/src/main/java/com/battlecruisers/yanullja/common/logging/CustomHttpLoggingFilter.java
server/src/main/java/com/battlecruisers/yanullja/common/logging/ReqResGuideLogFilter.java
server/src/main/resources/application.yml

로그북 삭제하고 직접 이쁜 로거 짜서 넣었습니다. 디버깅이 훨씬 편합니다.

feat(CustomLogger): delete Logbook and add custom http req/res logger

---

server/src/main/java/com/battlecruisers/yanullja/purchase/CustomPurchaseRepository.java
server/src/main/java/com/battlecruisers/yanullja/purchase/CustomPurchaseRepositoryImpl.java
server/src/main/java/com/battlecruisers/yanullja/purchase/PurchaseRepository.java
server/src/main/java/com/battlecruisers/yanullja/purchase/domain/PayType.java
server/src/main/java/com/battlecruisers/yanullja/purchase/dto/PurchaseDto.java
server/src/main/java/com/battlecruisers/yanullja/reservation/ReservationController.java
server/src/main/java/com/battlecruisers/yanullja/reservation/ReservationRepository.java
server/src/main/java/com/battlecruisers/yanullja/reservation/ReservationService.java
server/src/main/java/com/battlecruisers/yanullja/reservation/domain/Reservation.java
server/src/main/java/com/battlecruisers/yanullja/reservation/domain/ReservationStatus.java
server/src/main/java/com/battlecruisers/yanullja/reservation/dto/ReservationRequestDto.java
server/src/main/java/com/battlecruisers/yanullja/reservation/dto/ReservationResponseDto.java
server/src/main/java/com/battlecruisers/yanullja/reservation/dto/ReservationResponsePlaceDto.java
server/src/main/java/com/battlecruisers/yanullja/reservation/dto/ReservationResponseRoomDto.java
server/src/main/java/com/battlecruisers/yanullja/reservation/dto/ReservationResultDto.java
server/src/main/java/com/battlecruisers/yanullja/reservation/dto/ReservationResultPlaceDto.java
server/src/main/java/com/battlecruisers/yanullja/reservation/dto/ReservationResultRoomDto.java
server/src/main/java/com/battlecruisers/yanullja/reservation/exception/ErrorCode.java
server/src/main/java/com/battlecruisers/yanullja/reservation/exception/NotEnoughTotalRoomCountException.java
server/src/main/java/com/battlecruisers/yanullja/reservation/exception/ReservationNotFoundException.java
server/src/main/java/com/battlecruisers/yanullja/reservation/exception/StartDateNotAfterTodayException.java
server/src/main/java/com/battlecruisers/yanullja/reservation/exception/StartDateNotBeforeEndDateException.java

feat(reservation, purchase): 예약 조회 기능 구현

---

server/src/main/java/com/battlecruisers/yanullja/coupon/CouponService.java
server/src/main/java/com/battlecruisers/yanullja/coupon/domain/MemberCoupon.java
server/src/main/java/com/battlecruisers/yanullja/coupon/dto/MemberCouponDto.java

, MemberCoupon) : 쿠폰 서비스 내부에 위치한 getCalculateDiscountedPrice 메서드 오류 수정, MemberCoupon, MemberCouponDto에 테스트용 생성자 추가

refactor(CouponService, MemberCouponDto

---

server/src/main/java/com/battlecruisers/yanullja/common/config/GlobalExceptionHandler.java
server/src/main/java/com/battlecruisers/yanullja/common/exception/CustomValidationException.java
server/src/main/java/com/battlecruisers/yanullja/review/ReviewController.java
server/src/main/java/com/battlecruisers/yanullja/review/ReviewService.java
server/src/main/java/com/battlecruisers/yanullja/review/domain/Review.java
server/src/main/java/com/battlecruisers/yanullja/review/dto/ReviewSaveDto.java
server/src/main/java/com/battlecruisers/yanullja/review/example/WriteReviewOperation.java

후기 Controller에 Swagger example 적용하였습니다.

feat(Review): Add review controller swagger examples

---

README.md

docs(README.md): Update troubleshooting of Min Woo

---

README.md

코드 블록에 java 하이라이팅이 들어가도록 추가했습니다.

docs(README.md): Update code block to java code block

---

server/build.gradle
server/src/main/java/com/battlecruisers/yanullja/auth/controller/AuthController.java
server/src/main/java/com/battlecruisers/yanullja/member/MemberController.java
server/src/main/resources/logback-spring.xml

with minor build and xml fixes

docs(auth): add Auth / Member Controller Swagger annotations

---

README.md

코드와 한글로 작성한 설명 부분을 백틱으로 완전히 분리

Update README(edit backtick)
